/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Ziggy: typeof import('ziggy-js')['Ziggy']
  const route: typeof import('ziggy-js')['route']
}
