/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./Components/ApplicationLogo.vue')['default']
    Checkbox: typeof import('./Components/Checkbox.vue')['default']
    DangerButton: typeof import('./Components/DangerButton.vue')['default']
    Dropdown: typeof import('./Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./Components/DropdownLink.vue')['default']
    Footer: typeof import('./Components/Core/Footer/Footer.vue')['default']
    FooterElegant: typeof import('./Components/Core/Footer/FooterElegant.vue')['default']
    InputError: typeof import('./Components/InputError.vue')['default']
    InputLabel: typeof import('./Components/InputLabel.vue')['default']
    LessFooter: typeof import('./Components/Core/Footer/LessFooter.vue')['default']
    Modal: typeof import('./Components/Modal.vue')['default']
    NavLink: typeof import('./Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./Components/SecondaryButton.vue')['default']
    TextInput: typeof import('./Components/TextInput.vue')['default']
  }
}
